# Generated by Django 5.0 on 2025-02-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("RDM", "Random Thoughts"),
                    ("SCL", "School"),
                    ("PSL", "Personal"),
                    ("DRM", "Drama"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
